apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl-ip
    component: curl-ip
  name: curl-ip
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: curl-ip
      component: curl-ip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl-ip
        component: curl-ip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - curl-ip
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: CURLHOST
          value: https://172.30.0.1/version
        image: quay.io/rhn_support_sreber/curl@sha256:24ec2f92371d60e71cf5e705185cfb63bd788042c2a6ad505ad17b51ed37ecb0
        imagePullPolicy: IfNotPresent
        name: curl-ip
        ports:
        - containerPort: 8080
          name: curl-ip
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
