apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl-intra
    component: curl-intra
  name: curl-intra
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: curl-intra
      component: curl-intra
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl-intra
        component: curl-intra
    spec:
      containers:
      - env:
        - name: CURLHOST
          value: https://kubernetes.default.svc/version
        image: quay.io/rhn_support_sreber/curl@sha256:bc9c33e9a2b748f6b2da1983714e70951b35667ccd4cf9c12b4f0f502b5e5950
        imagePullPolicy: IfNotPresent
        name: curl-intra
        ports:
        - containerPort: 8080
          name: curl-intra
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
