apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping
    component: ping
  name: ping
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ping
      component: ping
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping
        component: ping
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ping
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: PINGHOST
          value: 10.130.2.18
        image: quay.io/rhn_support_sreber/ping:latest
        imagePullPolicy: IfNotPresent
        name: ping
        ports:
        - containerPort: 8080
          name: ping
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
